# Generated by Django 2.0 on 2017-12-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YodaPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('jedi', models.BooleanField(default=False)),
                ('sith', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('padawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoda_speak.Padawan')),
            ],
        ),
    ]
