# Generated by Django 2.0 on 2017-12-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoda_speak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yodaphrase',
            name='translation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yodaphrase',
            name='phrase',
            field=models.CharField(max_length=500),
        ),
    ]
