# Generated by Django 2.0 on 2017-12-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoda_speak', '0002_auto_20171206_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yodaphrase',
            name='phrase',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='yodaphrase',
            name='translation',
            field=models.TextField(null=True),
        ),
    ]
