# Generated by Django 2.0 on 2017-12-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoda_speak', '0003_auto_20171207_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padawan',
            name='userID',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
